name: Scrape latest List N, create DB, and publish to Vercel

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '57 5,14,20,23 * * *' # 1:57AM, 10:57AM, 4:57PM, 7:57PM 

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |-
        sudo apt-get update && sudo apt-get -y install jq python3-pip
        python3 -m pip install --user -U pip
        python3 -m pip install --user -r requirements.txt

    - name: Fetch latest data
      run: |-
        epa_json_data=$(curl "https://cfpub.epa.gov/wizards/disinfectants/includes/queries.cfc?method=getDisData&Keyword=&RegNum=&ActiveIng=All&ContactTime=&UseSite=&SurfType=" 2>/dev/null)
        echo "${epa_json_data}" | jq --monochrome-output . >list-N.json
        echo "${epa_json_data}" | python3 transform.py | jq --monochrome-output . >list-N.transformed.json

    - name: Rotate existing databases
      run: |-
        if [ -e disinfectants-prev.db ]; then mv -f disinfectants-prev.db disinfectants-prev-prev.db; fi
        if [ -e disinfectants.db ]; then mv -f disinfectants.db disinfectants-prev.db; fi
    - name: Create new database and set column order
      run: |-
        sqlite-utils insert disinfectants.db listN - --pk ID <list-N.transformed.json
        sqlite-utils transform disinfectants.db listN \
        --column-order EPA_reg_num \
        --column-order Risk_level \
        --column-order Active_ingredient \
        --column-order Product_name \
        --column-order Company \
        --column-order Use_site \
        --column-order Surface_type \
        --column-order Contact_time \
        --column-order Formulation_type \
        --column-order Follow_directions_for_this_virus \
        --column-order Date_on_List_N \
        --column-order Why_on_List_N \
        --column-order ID
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
    - name: Publish to Vercel
      env:
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      run: |-
        datasette publish vercel disinfectants.db \
        --project "list-n" \
        --title "Disinfectants Used for Addressing COVID" \
        --source "List N Tool COVID-19 Disinfectants" \
        --source_url "https://cfpub.epa.gov/giwiz/disinfectants/index.cfm" \
        --install datasette-vega \
        --setting default_page_size 3000 \
        --setting max_returned_rows 3000 \
        --setting default_facet_size 36 \
        --static static:static/ \
        --template-dir templates/ \
        --plugins-dir plugins/ \
        --metadata metadata.json \
        --token "$VERCEL_TOKEN"
